repositories {
    mavenCentral()
    google()
    maven {
        name "dairyReleases"
        url "https://repo.dairy.foundation/releases"
    }

}

dependencies {
//    implementation 'com.github.FTCPhantom16950:PhantomLib:1.0.3'
    implementation 'org.firstinspires.ftc:Inspection:11.0.0'
    implementation 'org.firstinspires.ftc:Blocks:11.0.0'
    //noinspection Aligned16KB
    implementation 'org.firstinspires.ftc:RobotCore:11.0.0'
    implementation 'org.firstinspires.ftc:RobotServer:11.0.0'
    implementation 'org.firstinspires.ftc:OnBotJava:11.0.0'
    implementation 'org.firstinspires.ftc:Hardware:11.0.0'
    implementation 'org.firstinspires.ftc:FtcCommon:11.0.0'
    implementation 'org.firstinspires.ftc:Vision:11.0.0'

    //noinspection GradleDependency
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation("page.j5155.AdvantageScope:lite:v26.0.0")
    implementation 'org.psilynx.psikit:core:0.1.0-beta1'
    implementation 'org.psilynx.psikit:ftc:0.1.0-beta1'

}